export type PatchNoteTone = "new" | "improved" | "fixed" | "system";

export interface PatchNoteEntry {
  version: string;
  releasedAt: string;
  title: string;
  summary: string;
  tone: PatchNoteTone;
  highlights: string[];
}

export interface RoadmapItem {
  title: string;
  status: "Completed" | "Planned" | "In progress" | "Next" | "Waiting";
  summary: string;
}

export const patchNotes: PatchNoteEntry[] = [
  {
    version: "3.2.19",
    releasedAt: "May 23, 2026",
    title: "Wishlist hearts on cards",
    summary: "DustyCards 3.2.19 adds quick wishlist hearts next to card add buttons.",
    tone: "improved",
    highlights: [
      "Search results and expansion card grids now show a heart next to the add button.",
      "Card detail actions include the same wishlist heart on desktop, mobile, and 3D detail views.",
      "Cards that are already wanted now show as active with a filled heart.",
    ],
  },
  {
    version: "3.2.18",
    releasedAt: "May 23, 2026",
    title: "Vendor buy estimate",
    summary: "DustyCards 3.2.18 adds a vendor buy percentage estimator to the Sell tab.",
    tone: "new",
    highlights: [
      "The Sell tab now lets you choose common vendor buy rates such as 70% or 80%.",
      "Estimated Sale Value now shows the matching vendor offer amount in EUR.",
      "The estimate updates instantly when the selected buy percentage changes.",
    ],
  },
  {
    version: "3.2.17",
    releasedAt: "May 23, 2026",
    title: "Consistent card previews",
    summary: "DustyCards 3.2.17 brings smaller card previews in Search and related card lists in line with collection and card detail images.",
    tone: "fixed",
    highlights: [
      "Search single-card previews now use the same card frame and crop behavior as collection tiles.",
      "Mover, value-driver, illustrator, deals, and want-planner card previews now share the same card image handling.",
      "Sealed product previews keep their full product image fit while card previews avoid the old light frame and extra border look.",
    ],
  },
  {
    version: "3.2.16",
    releasedAt: "May 23, 2026",
    title: "Printed number search padding",
    summary: "DustyCards 3.2.16 fixes printed card searches where the total after the slash is typed with a leading zero.",
    tone: "fixed",
    highlights: [
      "Searches such as 230/091 now also match cards stored as 230/91.",
      "Printed card-number aliases now handle leading zeroes on both sides of the slash.",
      "Added search tests for padded printed totals so exact number searches stay reliable.",
    ],
  },
  {
    version: "3.2.15",
    releasedAt: "May 23, 2026",
    title: "For Sale sold tracking",
    summary: "DustyCards 3.2.15 lets selected For Sale cards be marked sold with per-card or stack sale prices.",
    tone: "new",
    highlights: [
      "Added a Sold action to the Sell tab selection flow with a focused popup for EUR sale prices.",
      "Multiple selected cards can be priced one by one or sold as a stack total that is split across every card.",
      "The Sell tab now shows total sold value, sold card count, and sold P&L while active For Sale cards remain separate from collection totals.",
    ],
  },
  {
    version: "3.2.14",
    releasedAt: "May 23, 2026",
    title: "For Sale collection tab",
    summary: "DustyCards 3.2.14 adds a separate For Sale area for cards you want to sell without counting them in your collection value.",
    tone: "new",
    highlights: [
      "Added a Sell tab on the collection page with estimated sale value, priced-card count, and paid total.",
      "Cards saved to For Sale are excluded from collection totals, binder progress, wants ownership checks, categories, and collection market movers.",
      "Add, bulk-add, and edit flows can now save or move cards directly into For Sale.",
    ],
  },
  {
    version: "3.2.13",
    releasedAt: "May 23, 2026",
    title: "Mobile market density",
    summary: "DustyCards 3.2.13 makes Market and Deals easier to browse on phones while keeping market data warm for repeat visits.",
    tone: "improved",
    highlights: [
      "Deal listings now use a tighter mobile card layout with cleaner badges, compact price metrics, and less repeated marketplace text.",
      "Raw, graded, target, and sealed mover tiles are more compact so more market cards fit on screen without truncating key prices.",
      "Sealed movers now render in batches and use a stale-while-refresh cache so large market pages feel lighter after the first load.",
    ],
  },
  {
    version: "3.2.12",
    releasedAt: "May 22, 2026",
    title: "Binder density and mobile price fit",
    summary: "DustyCards 3.2.12 keeps mobile price deltas inside their card and lets binder tiles follow card layout density.",
    tone: "fixed",
    highlights: [
      "The mobile card detail percent change now wraps inside the main price tile instead of spilling into the next tile.",
      "Collection binder grids now use card layout size 1-4 instead of the general UI scale.",
      "Binder grids update from the active display settings on collection and wants views.",
    ],
  },
  {
    version: "3.2.11",
    releasedAt: "May 22, 2026",
    title: "Cleaner mobile card controls",
    summary: "DustyCards 3.2.11 cleans up mobile card actions and graded chart controls.",
    tone: "improved",
    highlights: [
      "Regular users now get a direct remove button instead of a three-dot menu with only one action.",
      "The graded slab selector now matches the compact switch styling and sits with the graded chart switches.",
      "Chart chips no longer repeat the EUR label, so grade labels such as PSA 10 stay readable on mobile.",
    ],
  },
  {
    version: "3.2.10",
    releasedAt: "May 22, 2026",
    title: "Submit variant guard",
    summary: "DustyCards 3.2.10 keeps Submit Card from previewing a CardMarket variant that is already in your library.",
    tone: "fixed",
    highlights: [
      "My variant is missing now skips known CardMarket product IDs and URLs during Firecrawl search.",
      "If Firecrawl still lands on an already listed set/card-number variant, the preview is blocked and asks for the exact CardMarket URL.",
      "Duplicate previews now keep Firecrawl credit counts accurate when a search or scrape was already used.",
    ],
  },
  {
    version: "3.2.9",
    releasedAt: "May 22, 2026",
    title: "Steadier card detail layout",
    summary: "DustyCards 3.2.9 keeps the desktop price chart in a more consistent position across different cards.",
    tone: "improved",
    highlights: [
      "Split the desktop card detail header into a compact fixed header and a separate Details panel.",
      "Moved variable fields such as pull odds, location, paid price, type, condition, tags, and notes below the graph.",
      "Reduced layout jumping between saved and unsaved cards with different amounts of metadata.",
    ],
  },
  {
    version: "3.2.8",
    releasedAt: "May 22, 2026",
    title: "Wants binder tiles aligned",
    summary: "DustyCards 3.2.8 brings the Wants binder planner tiles in line with the cleaner binder layout.",
    tone: "fixed",
    highlights: [
      "Applied the compact binder tile sizing to Missing by Binder on Wants.",
      "Matched Wants planner tiles to the same neutral surface, accent strip, logo frame, and spacing as collection binders.",
    ],
  },
  {
    version: "3.2.7",
    releasedAt: "May 22, 2026",
    title: "Cleaner binder and detail layout",
    summary: "DustyCards 3.2.7 tightens binder tiles and makes the desktop card detail page read as one cleaner layout.",
    tone: "improved",
    highlights: [
      "Made desktop binder tiles more compact with a calmer neutral surface and subtle set accent color.",
      "Removed the extra dark frame behind card images in the card detail preview.",
      "Reworked widescreen card details into a cleaner left media column and right content stack with fewer empty gaps.",
    ],
  },
  {
    version: "3.2.6",
    releasedAt: "May 22, 2026",
    title: "Cleaner graded scraping",
    summary: "DustyCards 3.2.6 tightens CardMarket graded parsing so raw 'PSA 10 potential' listings are not treated as slabs.",
    tone: "fixed",
    highlights: [
      "Ignored graded bait terms like potential, contender, candidate, raw, and ungraded when parsing seller comments.",
      "Recognized more real graded labels such as AOG, AiGrad, and generic Grade 10 rows with certificate context.",
      "Linked graded seller comments to the following row price first, which better matches CardMarket listing order.",
    ],
  },
  {
    version: "3.2.5",
    releasedAt: "May 22, 2026",
    title: "Submit name autocomplete",
    summary: "DustyCards 3.2.5 makes repeated card names faster to enter on Submit Card.",
    tone: "improved",
    highlights: [
      "Added game-aware card name autocomplete to the Submit Card form.",
      "Suggestions come from the local library, so typing names does not spend Firecrawl credits.",
    ],
  },
  {
    version: "3.2.4",
    releasedAt: "May 22, 2026",
    title: "Firecrawl credit offset",
    summary: "DustyCards 3.2.4 lets the live credit meter include Firecrawl requests made outside the production database.",
    tone: "fixed",
    highlights: [
      "Added a monthly Firecrawl credit offset so local/manual scrapes can be counted in the live Submit Card meter.",
      "Budget checks now include the offset before allowing another Firecrawl preview.",
    ],
  },
  {
    version: "3.2.3",
    releasedAt: "May 22, 2026",
    title: "Submit credit visibility",
    summary: "DustyCards 3.2.3 makes Firecrawl usage visible before submitting a CardMarket card.",
    tone: "improved",
    highlights: [
      "Added a Firecrawl credits panel to Submit Card with monthly usage, remaining budget, daily attempts, and API status.",
      "Added a lightweight usage endpoint that reads tracked credits without spending a Firecrawl request.",
    ],
  },
  {
    version: "3.2.2",
    releasedAt: "May 22, 2026",
    title: "Browse menu consistency",
    summary: "DustyCards 3.2.2 aligns every navigation surface around the same Browse placement.",
    tone: "fixed",
    highlights: [
      "Added Submit Card to the bottom of the header Browse menu as well.",
      "Kept the desktop sidebar, mobile More menu, and header navigation consistent.",
    ],
  },
  {
    version: "3.2.1",
    releasedAt: "May 22, 2026",
    title: "Submit Card navigation",
    summary: "DustyCards 3.2.1 keeps the submitted-card flow tucked into the normal browsing menu.",
    tone: "fixed",
    highlights: [
      "Moved Submit Card to the bottom of Browse on desktop and mobile.",
      "Kept the submitted-card flow grouped with sets, categories, and illustrators.",
    ],
  },
  {
    version: "3.2.0",
    releasedAt: "May 22, 2026",
    title: "Firecrawl submitted cards",
    summary: "DustyCards 3.2.0 adds a full CardMarket submit flow for cards that are missing from TCGGO.",
    tone: "new",
    highlights: [
      "Added a Submit Card page where signed-in users can preview and save missing Pokemon and One Piece CardMarket cards through Firecrawl.",
      "Saved submissions now create user-submitted sets and cards, add the submitter's collection copy automatically, and remain searchable for everyone.",
      "CardMarket graded rows are parsed from listing comments and saved into the normal graded price chart data.",
      "Added admin management for submitted cards, manual refreshes, deletion, and TCGGO takeover cleanup when official cards arrive later.",
      "Added a separate User tab in Expansions so submitted sets stay out of the normal TCGGO Pokemon and One Piece set lists.",
      "Added the Submit Card shortcut to the browsing navigation for quick access.",
    ],
  },
  {
    version: "3.1.18",
    releasedAt: "May 21, 2026",
    title: "Binder headers aligned",
    summary: "DustyCards 3.1.18 brings binder detail headers in line with expansion detail pages.",
    tone: "improved",
    highlights: [
      "Moved binder value charts into the same dashboard header structure used by expansion pages.",
      "Aligned owned and wants binder stat tiles into a clean two-by-two grid on the right.",
      "Reduced oversized binder logo spacing and tucked back links into the header area.",
    ],
  },
  {
    version: "3.1.17",
    releasedAt: "May 20, 2026",
    title: "Dark selection buttons",
    summary: "DustyCards 3.1.17 removes leftover white selection controls from collection and expansion card grids.",
    tone: "fixed",
    highlights: [
      "Updated Select buttons in expansion card grids to use the current dark chip theme.",
      "Aligned collection selection actions such as Select all, Clear, and Remove with the app theme.",
      "Kept disabled selection actions muted instead of bright white.",
    ],
  },
  {
    version: "3.1.16",
    releasedAt: "May 20, 2026",
    title: "Cleaner allocation bar",
    summary: "DustyCards 3.1.16 polishes the Collection Allocation bar on the Home dashboard.",
    tone: "fixed",
    highlights: [
      "Added spacing between allocation segments so the colors no longer touch directly.",
      "Rounded each segment inside a subtle dark rail for a cleaner dashboard look.",
      "Kept small allocation slices visible without making the bar feel cramped.",
    ],
  },
  {
    version: "3.1.15",
    releasedAt: "May 20, 2026",
    title: "More focused 3D card view",
    summary: "DustyCards 3.1.15 makes the desktop 3D card viewer match the card detail focus more closely.",
    tone: "improved",
    highlights: [
      "Opened desktop 3D cards closer to the viewer so they no longer feel smaller than the detail preview.",
      "Reduced the initial side angle so the card front stays readable and visually central.",
      "Kept the existing mobile 3D card-focused layout intact.",
    ],
  },
  {
    version: "3.1.14",
    releasedAt: "May 20, 2026",
    title: "Aligned expansion metric tiles",
    summary: "DustyCards 3.1.14 tightens the right-side metric tiles in expansion headers.",
    tone: "fixed",
    highlights: [
      "Made expansion header stat tiles fill the same grid row height on desktop.",
      "Aligned Pokemon sealed and pull-rate tiles with the pricing and card-count tiles.",
      "Kept One Piece expansion metric tiles on the same matching grid treatment.",
    ],
  },
  {
    version: "3.1.13",
    releasedAt: "May 20, 2026",
    title: "Expansion headers aligned",
    summary: "DustyCards 3.1.13 brings Pokemon and One Piece expansion detail headers in line with the rest of the app.",
    tone: "improved",
    highlights: [
      "Moved expansion charts and metrics into the same dashboard header structure used by Market.",
      "Reduced oversized expansion logos and header spacing so set pages feel consistent with other sections.",
      "Updated Pokemon pull-rate, sync, sealed, release, and value cards to use the current dark stat-card theme.",
    ],
  },
  {
    version: "3.1.12",
    releasedAt: "May 20, 2026",
    title: "Smarter home featured cards",
    summary: "DustyCards 3.1.12 fills the Home Featured Cards row with more cards when there is room.",
    tone: "improved",
    highlights: [
      "Expanded the Home Featured Cards pool so wide screens can use the empty space in the row.",
      "Added an adaptive desktop limit that only shows as many featured cards as fit cleanly.",
      "Kept mobile Featured Cards capped to complete rows so small screens do not become overloaded.",
    ],
  },
  {
    version: "3.1.11",
    releasedAt: "May 20, 2026",
    title: "Cleaner complete collection header",
    summary: "DustyCards 3.1.11 removes the duplicate collection section switch from the Complete Collection view.",
    tone: "improved",
    highlights: [
      "Hid the All, Loose, Binders, Sealed, and Graded switch bar on Complete Collection.",
      "Kept the Pokemon and One Piece library switch available when that library filter is enabled.",
      "Left the separate collection tabs reachable through the existing navigation so the page feels cleaner.",
    ],
  },
  {
    version: "3.1.10",
    releasedAt: "May 20, 2026",
    title: "More consistent home scaling",
    summary: "DustyCards 3.1.10 brings the Home collection views closer to the same scale as the rest of the app.",
    tone: "fixed",
    highlights: [
      "Reduced the oversized Home collection tab header, tab controls, and dashboard spacing.",
      "Made Featured Cards on Home follow the same card size and mobile column settings as the normal collection grid.",
      "Tightened Home dashboard panels, quick links, values, and progress rows so mobile and desktop feel more consistent.",
    ],
  },
  {
    version: "3.1.9",
    releasedAt: "May 20, 2026",
    title: "Solid dark popup theme",
    summary: "DustyCards 3.1.9 removes the see-through feel from Quick View and aligns app popups with the current dark theme.",
    tone: "fixed",
    highlights: [
      "Made the Wants Quick View popup and its sort/filter controls use opaque dark app surfaces.",
      "Updated the shared modal theme used by add, edit, remove, binder, and collection popups.",
      "Brought card and sealed detail popups onto the same solid dark overlay and panel treatment.",
    ],
  },
  {
    version: "3.1.8",
    releasedAt: "May 20, 2026",
    title: "Cleaner four-card mobile grids",
    summary: "DustyCards 3.1.8 makes the 4-cards-per-row phone layout keep names, prices, and actions readable.",
    tone: "fixed",
    highlights: [
      "Changed the 4-column mobile card layout so names can wrap instead of being cut off after one short line.",
      "Stacked price and trend/action controls on ultra-compact cards so prices no longer lose space to side buttons.",
      "Extended mobile bottom safe spacing across logged-in pages so card prices can scroll above the bottom nav.",
    ],
  },
  {
    version: "3.1.7",
    releasedAt: "May 20, 2026",
    title: "Mobile home scroll safe area",
    summary: "DustyCards 3.1.7 fixes the phone homepage bottom spacing so the mobile nav no longer covers the last content.",
    tone: "fixed",
    highlights: [
      "Restored the mobile bottom safe area for the homepage collection shell.",
      "Made the safe-area padding specific enough to override the shared page container padding.",
      "Kept desktop page spacing unchanged while giving phone screens enough room below the final card.",
    ],
  },
  {
    version: "3.1.6",
    releasedAt: "May 20, 2026",
    title: "Larger centered mobile 3D cards",
    summary: "DustyCards 3.1.6 makes mobile 3D cards larger, better centered, and more responsive to phone screen sizes.",
    tone: "fixed",
    highlights: [
      "Added a mobile-specific 3D camera distance so phone cards no longer inherit the roomier desktop framing.",
      "Centered the card above the collapsed details sheet with a smaller vertical offset on narrow screens.",
      "Changed mobile 3D fitting to use the card bounds so the preview scales cleanly on both regular and smaller phones.",
    ],
  },
  {
    version: "3.1.5",
    releasedAt: "May 20, 2026",
    title: "Fullscreen mobile 3D cards",
    summary: "DustyCards 3.1.5 gives the mobile 3D viewer more room by collapsing card details into a bottom sheet.",
    tone: "improved",
    highlights: [
      "Changed the mobile 3D viewer details panel to start collapsed at the bottom of the screen.",
      "Kept the 3D canvas full-screen on phones so the card stays the visual focus.",
      "Added a tap-to-expand bottom sheet for pricing, graded pricing, CardMarket, and Add actions.",
    ],
  },
  {
    version: "3.1.4",
    releasedAt: "May 20, 2026",
    title: "Home featured card detail fix",
    summary: "DustyCards 3.1.4 brings Featured Cards on Home in line with the rest of the card grid experience.",
    tone: "fixed",
    highlights: [
      "Restyled Home Featured Cards to use the same premium collection tile treatment as the rest of the app.",
      "Changed Featured Cards from expansion links into direct card detail modal triggers.",
      "Kept collection item details such as binder, cost basis, condition, language, notes, tags, and grading data attached when opening the card.",
    ],
  },
  {
    version: "3.1.3",
    releasedAt: "May 20, 2026",
    title: "Cleaner mobile More menu",
    summary: "DustyCards 3.1.3 removes the redundant Search shortcut from the phone More menu.",
    tone: "improved",
    highlights: [
      "Removed Search from the mobile More menu because phone search already has its own header button.",
      "Kept Browse focused on sets, categories, and illustrators.",
    ],
  },
  {
    version: "3.1.2",
    releasedAt: "May 20, 2026",
    title: "Mobile switch sizing hotfix",
    summary: "DustyCards 3.1.2 fixes oversized segmented switches on phone screens.",
    tone: "fixed",
    highlights: [
      "Removed the broad mobile grid rendering optimization that made segmented controls reserve card-sized rows on iPhone.",
      "Restored compact sizing for the Collection card layout switch and other mobile tab or filter switches.",
    ],
  },
  {
    version: "3.1.1",
    releasedAt: "May 20, 2026",
    title: "Mobile market polish",
    summary: "DustyCards 3.1.1 cleans up the eBay Deals header, mobile search contrast, illustrator sorting, and reset-password action styling.",
    tone: "improved",
    highlights: [
      "Changed eBay Deals stats to the shared header stat cards with clearer icons, rate-limit color states, and fallback intro text when no reference price is selected.",
      "Made the eBay Deals and forgot-password submit buttons read as stronger primary actions in the dark app shell.",
      "Polished the Illustrators sort toggle so it wraps cleanly on narrow screens and matches the violet active state used elsewhere.",
      "Darkened the mobile search overlay background so search suggestions stay readable over page content.",
      "Added a mobile UI review script for quickly capturing key logged-in, logged-out, menu, search, and card-detail screens.",
    ],
  },
  {
    version: "3.1.0",
    releasedAt: "May 20, 2026",
    title: "Sharper dashboard and mobile polish",
    summary: "DustyCards 3.1 tightens the portfolio dashboard, chart experience, page headers, sidebar, mobile card views, and card detail flow.",
    tone: "improved",
    highlights: [
      "Rebuilt the home dashboard around a larger collection value chart, clearer ROI, spend, priced coverage, completion, item totals, featured cards, allocation, and top set progress.",
      "Added a dedicated dashboard chart layout for collection, wants, movers, and expansion pages with cleaner range controls, compact value axis labels, percentage deltas, and better responsive sizing.",
      "Simplified page headers across categories, deals, expansions, movers, wants, settings, and detail screens so stats and controls scan faster on desktop and mobile.",
      "Polished the desktop sidebar, active states, dark background, and mobile scroll performance for a steadier app shell.",
      "Cleaned up card grids and card detail views with lighter mobile image loading, steadier tile heights, violet selection states, denser mobile info cards, and a direct CardMarket action.",
    ],
  },
  {
    version: "3.0.0",
    releasedAt: "May 19, 2026",
    title: "Premium collection UI overhaul",
    summary: "DustyCards now uses the compact premium binder-style interface across collection, detail, wants, market, search, and settings.",
    tone: "new",
    highlights: [
      "Reworked the app shell, navigation, headers, tabs, filters, cards, tiles, modals, and empty states into one darker collector-focused visual system.",
      "Made collection, binder, sealed, wants, movers, search, expansion, category, illustrator, account, and settings screens denser and more image-led on mobile and desktop.",
      "Refined card detail pages with a widescreen market layout, compact actions, better pricing panels, improved 3D handling, and consistent raw, graded, sealed, and related sections.",
      "Added the new market structure with risers, drops, raw, graded, targets, sealed, and deals views while preserving existing collection actions and links.",
    ],
  },
  {
    version: "2.1.17",
    releasedAt: "May 18, 2026",
    title: "Cleaner card layout labels",
    summary: "Mobile card layout controls now use simple numeric labels: 1, 2, 3, and 4.",
    tone: "improved",
    highlights: [
      "Changed mobile card layout buttons from layout jargon to plain numbers.",
      "Applied the numeric labels across collection overview, card grids, expansion grids, and settings.",
      "Kept the underlying one, two, three, and four cards-per-row behavior unchanged.",
    ],
  },
  {
    version: "2.1.16",
    releasedAt: "May 18, 2026",
    title: "Cleaner mobile binder cards",
    summary: "Wantlist planner and collection binder tiles now show fewer, clearer stats on phone.",
    tone: "improved",
    highlights: [
      "Reduced mobile Wantlist planner binder metrics to the most useful scan info.",
      "Hid tiny secondary metric text on phone while keeping it available on desktop.",
      "Simplified collection binder tiles on mobile so linked binders rely on the progress bar plus value stats.",
    ],
  },
  {
    version: "2.1.15",
    releasedAt: "May 18, 2026",
    title: "Widescreen quick view room",
    summary: "Wants Quick View now uses widescreen mode more aggressively so more missing cards fit without scrolling.",
    tone: "improved",
    highlights: [
      "Made the Quick View popup much wider in widescreen mode starting at desktop widths.",
      "Moved the wide-mode header into the side panel so the card list gets more vertical space.",
      "Expanded the missing-card list to 3, 4, or 5 columns depending on available screen width.",
    ],
  },
  {
    version: "2.1.14",
    releasedAt: "May 18, 2026",
    title: "Catalog set 403 guard",
    summary: "Background price refresh now skips blocked catalog set cardlists instead of failing the whole run.",
    tone: "fixed",
    highlights: [
      "Extended the TCGGO 403 recovery to optional catalog set cardlist requests.",
      "Keeps the price refresh batch moving when a single remote catalog set is blocked.",
      "Still leaves quota and non-catalog failures visible so real scraper issues are not hidden.",
    ],
  },
  {
    version: "2.1.13",
    releasedAt: "May 18, 2026",
    title: "Sealed value driver details",
    summary: "Sealed items in Movers value changes now open their sealed detail popup instead of jumping to the expansion page.",
    tone: "fixed",
    highlights: [
      "Changed sealed value-driver tiles from expansion links into sealed product detail popups.",
      "Kept raw card value-driver behavior unchanged so cards still open card details.",
      "Reused the existing sealed product modal for consistent sealed pricing and collection details.",
    ],
  },
  {
    version: "2.1.12",
    releasedAt: "May 18, 2026",
    title: "TCGGO catalog refresh guard",
    summary: "Background price refresh now keeps running when TCGGO blocks the optional One Piece catalog endpoint.",
    tone: "fixed",
    highlights: [
      "Changed TCGGO HTTP failures into typed status errors so the scraper can react safely.",
      "Made the auto catalog preflight skip a 403 catalog response instead of failing the whole price batch.",
      "Kept quota errors and real price refresh failures visible so broken core scraping is still reported.",
    ],
  },
  {
    version: "2.1.11",
    releasedAt: "May 18, 2026",
    title: "Larger quick view card thumbnails",
    summary: "Wants Quick View rows now show larger card previews on phone and desktop.",
    tone: "improved",
    highlights: [
      "Increased Quick View card thumbnails so the artwork is easier to recognize.",
      "Gave rows a touch more breathing room while keeping the popup compact.",
      "Kept the add action aligned and the modal within the viewport on mobile and desktop.",
    ],
  },
  {
    version: "2.1.10",
    releasedAt: "May 18, 2026",
    title: "Simpler card layout labels",
    summary: "Mobile collection density now uses a clearer one, two, three, and four card order.",
    tone: "fixed",
    highlights: [
      "Changed the mobile card layout controls to follow the one, two, three, and four card order.",
      "Kept the four-card option working on phones.",
      "Applied the same ordering to collection overview, card grids, expansion grids, and phone settings.",
    ],
  },
  {
    version: "2.1.9",
    releasedAt: "May 18, 2026",
    title: "Clearer collection size controls",
    summary: "Collection card sizing is now easier to understand and available directly from the overview on phone.",
    tone: "improved",
    highlights: [
      "Renamed mobile card density buttons from 4, S, M, and L to clearer card-per-row labels.",
      "Added a compact Card layout control above the collection overview sections.",
      "Kept desktop controls clear with Small, Medium, and Large labels.",
    ],
  },
  {
    version: "2.1.8",
    releasedAt: "May 18, 2026",
    title: "PSA slab and four-card mobile polish",
    summary: "PSA slabs now have a detailed label back, the mobile 3D card opens higher, and phone grids can switch to four cards per row.",
    tone: "fixed",
    highlights: [
      "Added a PSA-style back label texture in the 3D slab viewer instead of the blank label back.",
      "Raised the mobile 3D card framing so the card no longer sits over the detail panel.",
      "Added a visible 4/S/M/L mobile size control on collection and expansion card grids.",
      "Added the four-card phone layout option to settings so it can be saved as the mobile default.",
    ],
  },
  {
    version: "2.1.7",
    releasedAt: "May 18, 2026",
    title: "Wants Quick View edge alignment",
    summary: "Mobile Wants Quick View content now lines up evenly with the popup sides.",
    tone: "fixed",
    highlights: [
      "Removed the mobile right-side spacing that made the Quick View header and tiles look offset.",
      "Moved the mobile close action into the compact content row so it no longer narrows the list.",
      "Kept the desktop Quick View header and side panel unchanged.",
    ],
  },
  {
    version: "2.1.6",
    releasedAt: "May 18, 2026",
    title: "Wants Quick View filter polish",
    summary: "The mobile Wants Quick View sort and filter controls are cleaner, more compact, and easier to tap.",
    tone: "fixed",
    highlights: [
      "Changed mobile Quick View sorting into an even Number, Price, and Name segmented row.",
      "Changed mobile filtering into a matching Show row for All, Priced, and No price.",
      "Kept the controls compact so the missing-card list still starts quickly on phones.",
    ],
  },
  {
    version: "2.1.5",
    releasedAt: "May 18, 2026",
    title: "Mobile Wants Quick View cleanup",
    summary: "Wants Quick View now opens straight into the card list on phones, while desktop keeps the contextual header and side panel.",
    tone: "fixed",
    highlights: [
      "Removed the Quick View title header from the mobile popup.",
      "Hid the binder artwork and summary panel on phone so the missing-card list appears immediately.",
      "Kept the desktop Quick View header and side context intact.",
    ],
  },
  {
    version: "2.1.4",
    releasedAt: "May 18, 2026",
    title: "3D card mobile sizing hotfix",
    summary: "The mobile 3D card viewer now opens a little smaller so it leaves cleaner room for the detail panel.",
    tone: "fixed",
    highlights: [
      "Adjusted only the mobile 3D camera sizing presets for small, medium, and large modes.",
      "Kept the desktop 3D sizing unchanged.",
      "Preserved the larger premium viewer feel while reducing overlap with the mobile details panel.",
    ],
  },
  {
    version: "2.1.3",
    releasedAt: "May 18, 2026",
    title: "Wants Quick View modal hotfix",
    summary: "Wants Quick View now opens as a real popup on mobile instead of expanding inside the binder tile.",
    tone: "fixed",
    highlights: [
      "Moved Wants Quick View into a portal-based modal rendered outside the tile layout.",
      "Kept the binder tile height stable when opening Quick View on mobile.",
      "Preserved the dark glassy modal styling, backdrop close behavior, and internal scrolling.",
    ],
  },
  {
    version: "2.1.2",
    releasedAt: "May 18, 2026",
    title: "Mobile tab and quick view polish",
    summary: "Collection breakdown, segmented tabs, card detail actions, and Wants Quick View received a tighter mobile polish pass.",
    tone: "fixed",
    highlights: [
      "Made the portfolio breakdown shorter on phones while keeping values, counts, and percentages readable.",
      "Removed the extra outer frame around the collection view tabs so only the segmented control remains.",
      "Standardized mobile segmented tabs across collection, movers, settings, account, and sync views with no horizontal tab scrolling.",
      "Gave the card detail remove action a subtle destructive red tint that still fits the dark premium UI.",
      "Changed Wants Quick View into a safe-area-aware floating mobile popup with its own scrollable body and clear close behavior.",
    ],
  },
  {
    version: "2.1.1",
    releasedAt: "May 18, 2026",
    title: "Mobile hover and card tile cleanup",
    summary: "Mobile hover information is now accessible without extra card tile info buttons, and card detail action icons are better aligned.",
    tone: "fixed",
    highlights: [
      "Added a mobile long-press tooltip layer for hover-only labels and title/aria-label information.",
      "Removed the extra info button from card tiles so tapping the card itself opens the full details.",
      "Centered the remove icon inside the card detail action button.",
      "Made Pull Rate hover panels clearer on mobile by changing the hint to Tap and focusing the panel on tap.",
    ],
  },
  {
    version: "2.1.0",
    releasedAt: "May 18, 2026",
    title: "Compact mobile detail controls",
    summary: "Card detail actions, collection tabs, 3D viewing, and price history controls were tightened for mobile without changing the DustyCards look.",
    tone: "improved",
    highlights: [
      "Moved card detail actions into a compact top-right icon group with admin-only History and Refresh controls.",
      "Made the collection overview tabs fit on mobile without horizontal scrolling and preserved scroll position when switching tabs.",
      "Removed the bulky mobile modal header and kept close buttons floating with safe tap targets.",
      "Restored the 3D card viewer to a larger premium size while preventing close taps from reopening the card.",
      "Placed Price History language buttons next to Raw and Graded so the controls take less vertical space.",
    ],
  },
  {
    version: "2.0.1",
    releasedAt: "May 18, 2026",
    title: "Mobile collection polish",
    summary: "Collection overview, card detail, 3D view, and price history panels are now easier to use on small screens.",
    tone: "fixed",
    highlights: [
      "Made the collection breakdown cards readable on mobile with one or two columns instead of cramped three-column truncation.",
      "Changed overview tabs into mobile-safe scrollable tabs that keep every label reachable and readable.",
      "Compacted the card detail header and action row on phones while keeping desktop behavior intact.",
      "Reduced mobile price chart height and replaced noisy technical status text with clearer live price chips.",
      "Improved modal width, safe-area spacing, scroll-to-top behavior, and 3D close handling so the card cannot reopen from the same tap.",
    ],
  },
  {
    version: "2.0.0",
    releasedAt: "May 18, 2026",
    title: "Binder and graded card upgrade",
    summary: "Mobile binder flows, graded slabs, 3D card viewing, and collection spend language received a bigger polish pass.",
    tone: "new",
    highlights: [
      "Bumped the app release to 2.0.0 for the larger binder and graded card refresh.",
      "Changed binder spend language to Overall Spend so shared collection costs read more clearly.",
      "Moved Add Binder on mobile into a centered floating popup and made linked binder suggestions harder to miss.",
      "Added BGS subgrade entry when adding or editing graded BGS cards, while keeping the selected raw condition attached to the graded copy.",
      "Improved BGS slab previews and added a real BGS slab treatment in the 3D card viewer.",
      "Matched the PSA slab back in the 3D viewer more closely to the existing PSA card model.",
      "Added an Add button beside CardMarket inside the 3D card model view.",
      "Reduced holo effect readability loss so card text stays sharper while preserving the foil feel.",
      "Added a mobile four-card binder/card grid option and a tap info popup for mobile card details.",
      "Cleaned up the Illustrators header so its stats no longer duplicate the same count.",
    ],
  },
  {
    version: "1.1.0",
    releasedAt: "May 18, 2026",
    title: "Dashboard and workflow refresh",
    summary: "Collection, Wants, Movers, search, admin tooling, and pricing behavior were cleaned up into a bigger release.",
    tone: "new",
    highlights: [
      "Bumped the app release to 1.1.0 for the larger dashboard and workflow refresh.",
      "Rebuilt the Collection header into a dashboard layout with a live value chart, stat cards, and game switcher.",
      "Added the Collection Breakdown panel for raw, graded, and sealed value mix with a cleaner allocation bar.",
      "Moved the Breakdown panel above the collection view tabs and matched it to the main header styling.",
      "Replaced the old collection tab buttons with the shared segmented navigation component.",
      "Rebuilt the Wants header with the same dashboard chart and stat card layout as Collection.",
      "Split Wants page content into a cleaner client section so search and planner state are easier to manage.",
      "Upgraded Wants binder quick view into a modal with binder artwork, progress, stats, and a full binder link.",
      "Added quick view sorting by number, price, and name.",
      "Added quick view filters for all, priced, and unpriced missing cards.",
      "Added search match previews inside want binder tiles.",
      "Rebuilt the Movers header with market pulse charting, stat cards, game switcher, scope controls, and source controls.",
      "Removed duplicated Movers control strips from the value, raw, graded, target, and sealed mover sections.",
      "Added shared GameFilterSwitch and SegmentedNavLinks components for consistent navigation controls.",
      "Improved search for exact printed numbers like 002/203.",
      "Improved search for compact printed references like 002203 and space-separated references like 2 203.",
      "Stopped exact printed-number searches from falling into fuzzy fallback when there is no exact match.",
      "Made short text search less noisy by matching tiny text tokens by prefix instead of broad substring hits.",
      "Added tests for printed-number search aliases, exact search behavior, and short text matching.",
      "Added admin-only Firecrawl settings in Settings.",
      "Added the /api/admin/firecrawl endpoint with server-side admin checks.",
      "Added Firecrawl API key and monthly credit budget configuration in the env example.",
      "Ignored local .firecrawl output so scraped/debug files do not get committed accidentally.",
      "Aligned price refreshes to shared tier slots instead of private rolling countdowns per card.",
      "Updated price refresh labels and tests for shared 12h and daily schedules.",
      "Added card detail collection location labels and a remove-saved-copy action.",
      "Polished BGS slab previews with a proper gold label and grade descriptors.",
      "Added fixed range and hidden range-control support to price charts.",
      "Improved chart touch behavior on mobile.",
      "Reduced BGS 10 grading target scores so harder grades are weighted more realistically.",
      "Improved card browser toolbar layouts, including compact toolbar mode without search.",
      "Stretched grid layouts more consistently across search, categories, illustrators, expansions, movers, wants, and binders.",
      "Added portfolio and wants layout sizing variables for more consistent header panel heights.",
    ],
  },
  {
    version: "1.0.25",
    releasedAt: "May 17, 2026",
    title: "Roadmap focus update",
    summary: "The roadmap now reflects that price intelligence is complete and the next work is admin data quality plus Deal Radar v2.",
    tone: "system",
    highlights: [
      "Marked the price intelligence layer as completed.",
      "Added an admin-only data quality center as the next diagnostics step.",
      "Moved Deal Radar v2 into next-up focus for confidence, risk, shipping, and seller context.",
    ],
  },
  {
    version: "1.0.24",
    releasedAt: "May 17, 2026",
    title: "Sealed language charts",
    summary: "Sealed product charts now handle CardMarket language prices the same way card detail does.",
    tone: "improved",
    highlights: [
      "Sealed detail now has Market, EU, DE, FR, ES, and IT chart series where data is available.",
      "The selected sealed series drives the chart, current price, 7D average, and 30D average.",
      "Removed the duplicate language price rows so sealed pricing looks cleaner and closer to normal cards.",
    ],
  },
  {
    version: "1.0.23",
    releasedAt: "May 17, 2026",
    title: "Sealed detail and sync polish",
    summary: "Sealed product detail, pricing freshness, local sync safety, modal styling, and promo numbers were cleaned up.",
    tone: "improved",
    highlights: [
      "Sealed product detail now matches the normal card detail layout more closely.",
      "Card detail is clearer about eBay sold pricing freshness and avoids stale graded values overriding stronger raw prices.",
      "Local development no longer runs background price sync unless it is explicitly enabled.",
      "Collection popups now share the same clean glassy action row without the old dark footer bar.",
      "Black Star promo card numbers now show the printed single promo number, such as SM241.",
    ],
  },
  {
    version: "1.0.22",
    releasedAt: "May 17, 2026",
    title: "Card metadata restored",
    summary: "Card tiles show the card number and clickable set name again.",
    tone: "fixed",
    highlights: [
      "Restored the original collection card metadata line.",
      "Restored set links in card rows and grids where they were available before.",
    ],
  },
  {
    version: "1.0.21",
    releasedAt: "May 17, 2026",
    title: "Cleaner card number labels",
    summary: "Card grids now keep the printed card number visible without repeating the same set name on every card.",
    tone: "improved",
    highlights: [
      "Collection card rows, tables, and tiles now show only the card number in the compact meta line.",
      "Expansion card rows and grids use the same cleaner number-only treatment.",
    ],
  },
  {
    version: "1.0.20",
    releasedAt: "May 17, 2026",
    title: "Printed card numbers",
    summary: "Cards can now show and search the number printed on the card, like 144/131.",
    tone: "new",
    highlights: [
      "Added stored printed card numbers separate from the raw sync number.",
      "Backfilled Pokemon printed references from TCGdex official set counts.",
      "Search can match printed references while keeping sync-safe raw numbers intact.",
    ],
  },
  {
    version: "1.0.19",
    releasedAt: "May 17, 2026",
    title: "Want quick view number clarity",
    summary: "Card numbers in want binder quick view are easier to read.",
    tone: "improved",
    highlights: [
      "Card number badges are larger and higher contrast.",
      "Mobile quick view keeps card identity easier to scan.",
    ],
  },
  {
    version: "1.0.18",
    releasedAt: "May 17, 2026",
    title: "Wantlist quick view polish",
    summary: "Want binder quick view is cleaner, focused, and can add cards directly.",
    tone: "improved",
    highlights: [
      "Quick view rows now prioritize card image, name, number, and rarity.",
      "Prices are smaller so the missing card info is easier to scan.",
      "Quick view card rows are clickable and open card detail.",
      "Only one quick view opens at once, without stretching the full tile row.",
      "The old hide button is now an add-to-binder action.",
    ],
  },
  {
    version: "1.0.17",
    releasedAt: "May 17, 2026",
    title: "Want binder detail pages",
    summary: "Wantlist binder tiles now open a full binder-style missing cards page.",
    tone: "improved",
    highlights: [
      "Clicking a want binder opens a dedicated page with header, chart, and missing cards.",
      "Planner tiles keep the same compact footprint as collection binders.",
      "Quick view is still available as a small secondary action on each tile.",
    ],
  },
  {
    version: "1.0.16",
    releasedAt: "May 17, 2026",
    title: "Want binder tile sizing",
    summary: "Wantlist planner binder tiles now match the collection binder tile footprint.",
    tone: "fixed",
    highlights: [
      "Uses the same fixed tile width as collection binders.",
      "Collapsed wants tiles no longer show the extra top-missing block.",
      "Missing cards stay available after clicking the binder tile open.",
    ],
  },
  {
    version: "1.0.15",
    releasedAt: "May 17, 2026",
    title: "Wantlist planner polish",
    summary: "Binder wants now load immediately and use clickable binder-style tiles.",
    tone: "improved",
    highlights: [
      "Missing binder wants are prepared before the Wants page renders.",
      "Planner binders now look like collection binder tiles with wants-focused metrics.",
      "Clicking a binder tile opens the missing card list directly inside the tile.",
    ],
  },
  {
    version: "1.0.14",
    releasedAt: "May 17, 2026",
    title: "Roadmap status cleanup",
    summary: "Wantlist planner is now marked completed in the roadmap.",
    tone: "improved",
    highlights: [
      "Added a completed roadmap state.",
      "Marked Wantlist planner as completed after the live release.",
      "Kept the upcoming roadmap focused on the next larger features.",
    ],
  },
  {
    version: "1.0.13",
    releasedAt: "May 17, 2026",
    title: "Wantlist planner",
    summary: "Linked binder missing cards now flow into Wants automatically.",
    tone: "new",
    highlights: [
      "Missing cards from linked set binders are added to Wants without a manual repair step.",
      "Wants now groups binder goals into a compact Missing by Binder planner.",
      "Hiding a planner card keeps it out of auto-sync until hidden cards are reset.",
    ],
  },
  {
    version: "1.0.12",
    releasedAt: "May 17, 2026",
    title: "Card detail cleanup",
    summary: "Removed the noisy price intelligence strip from card detail.",
    tone: "fixed",
    highlights: [
      "Kept the compact price status line under the chart.",
      "Removed duplicated confidence, source, freshness, sample, and history tiles.",
      "Card detail is cleaner again on desktop and mobile.",
    ],
  },
  {
    version: "1.0.11",
    releasedAt: "May 17, 2026",
    title: "Price intelligence layer",
    summary: "Card detail now explains price confidence instead of only showing raw numbers.",
    tone: "new",
    highlights: [
      "Added compact confidence, source, freshness, and history signals under the price chart.",
      "eBay sold graded prices now show sample quality and USD to EUR conversion context.",
      "Thin-data warnings make noisy prices easier to spot before buying or selling.",
    ],
  },
  {
    version: "1.0.9",
    releasedAt: "May 17, 2026",
    title: "Roadmap cleanup",
    summary: "Roadmap now focuses on bigger product improvements instead of small bug-fix tasks.",
    tone: "improved",
    highlights: [
      "Removed bug-fix style roadmap items.",
      "Added larger feature ideas for collection, deals, grading, alerts, and sharing.",
      "Kept Japanese support visible as waiting on TCGGO data.",
    ],
  },
  {
    version: "1.0.8",
    releasedAt: "May 17, 2026",
    title: "Expanded roadmap",
    summary: "Roadmap now lists more useful longer-term app improvements.",
    tone: "improved",
    highlights: [
      "Added Japanese support as a waiting-on-data-source item.",
      "Added clearer next improvements for pricing, collection, sync, and mobile UX.",
      "Roadmap stays compact inside the Updates tab.",
    ],
  },
  {
    version: "1.0.7",
    releasedAt: "May 17, 2026",
    title: "Patch notes and roadmap",
    summary: "Added a compact Updates tab in Settings so every release has a clear note.",
    tone: "new",
    highlights: [
      "New Patch Notes window in Settings.",
      "Small roadmap section for upcoming app polish.",
      "Patch notes are stored in a dedicated app file for each release.",
    ],
  },
  {
    version: "1.0.6",
    releasedAt: "May 17, 2026",
    title: "Smarter binder tiles",
    summary: "Binder tiles now show what the set is doing, not only lifetime P&L.",
    tone: "improved",
    highlights: [
      "Added completion percentage and missing card count.",
      "Added recent binder value movement with percent change.",
      "Added ROI under P&L while keeping the tile compact on mobile.",
    ],
  },
  {
    version: "1.0.5",
    releasedAt: "May 17, 2026",
    title: "Consistent slab previews",
    summary: "Card detail slabs now match the same visual style used on collection overview tiles.",
    tone: "fixed",
    highlights: [
      "Removed the separate detail slab look.",
      "Matched wrapper, sizing behavior, and tile styling.",
      "Checked desktop and mobile card detail layouts.",
    ],
  },
  {
    version: "1.0.4",
    releasedAt: "May 17, 2026",
    title: "Account page refresh",
    summary: "Account was rebuilt into a cleaner, more professional account area.",
    tone: "improved",
    highlights: [
      "New account overview layout.",
      "Cleaner security and admin sections.",
      "Better mobile spacing and account stats.",
    ],
  },
  {
    version: "1.0.3",
    releasedAt: "May 16, 2026",
    title: "Settings control center",
    summary: "Settings was reorganized into focused tabs with less duplicate information.",
    tone: "improved",
    highlights: [
      "Added Preferences, Collection, System, and Sync tabs.",
      "Grouped related controls into smaller panels.",
      "Moved sync tooling into one cleaner control area.",
    ],
  },
];

export const roadmapItems: RoadmapItem[] = [
  {
    title: "Japanese card support",
    status: "Waiting",
    summary: "Add Japanese library and price flows when TCGGO exposes reliable Japanese data.",
  },
  {
    title: "Price intelligence layer",
    status: "Completed",
    summary: "Source confidence, eBay sold sample context, currency conversion, stale-price handling, and thin-data warnings are now visible in card and sealed detail.",
  },
  {
    title: "Admin data quality center",
    status: "Next",
    summary: "Admin-only diagnostics for missing images, missing source URLs, stale prices, empty histories, and unavailable price states.",
  },
  {
    title: "Price alerts and watch rules",
    status: "Planned",
    summary: "Let users watch cards, binders, sealed, and wants for target prices or sudden movement.",
  },
  {
    title: "Portfolio analytics",
    status: "Planned",
    summary: "Track allocation by set, era, rarity, language, graded/raw, sealed, and total exposure.",
  },
  {
    title: "Binder goals",
    status: "Planned",
    summary: "Rank missing cards by price, rarity, completion impact, and best next buys for each binder.",
  },
  {
    title: "Grading decision helper",
    status: "Planned",
    summary: "Compare raw value, graded comps, expected grade upside, fees, and likely ROI.",
  },
  {
    title: "Deal Radar v2",
    status: "Next",
    summary: "Add match confidence, risk flags, shipping impact, seller context, and target-margin presets.",
  },
  {
    title: "Wantlist planner",
    status: "Completed",
    summary: "Missing cards from linked binders are now automatically grouped into Wants.",
  },
  {
    title: "Sealed portfolio tools",
    status: "Planned",
    summary: "Track sealed entry price, market movement, position size, ROI, and product-level liquidity.",
  },
  {
    title: "Market timeline",
    status: "Planned",
    summary: "Create a clean timeline of collection value changes, biggest movers, buys, and sold/listing events.",
  },
  {
    title: "Smart collection import",
    status: "Planned",
    summary: "Import CSV or pasted lists, auto-match cards, detect duplicates, and preview changes before saving.",
  },
  {
    title: "Collection export center",
    status: "Planned",
    summary: "Export collection, binders, sealed, wants, and valuation snapshots for backup or spreadsheets.",
  },
  {
    title: "Shareable binder pages",
    status: "Planned",
    summary: "Generate read-only public or private links for selected binders and portfolio views.",
  },
  {
    title: "Personal dashboard widgets",
    status: "Planned",
    summary: "Let users choose which overview modules appear first, with compact cards for their workflow.",
  },
];
