export type PatchNoteTone = "new" | "improved" | "fixed" | "system";

export interface PatchNoteEntry {
  version: string;
  releasedAt: string;
  title: string;
  summary: string;
  tone: PatchNoteTone;
  highlights: string[];
}

export interface RoadmapItem {
  title: string;
  status: "Completed" | "Planned" | "In progress" | "Next" | "Waiting";
  summary: string;
}

export const patchNotes: PatchNoteEntry[] = [
  {
    version: "2.1.4",
    releasedAt: "May 18, 2026",
    title: "3D card mobile sizing hotfix",
    summary: "The mobile 3D card viewer now opens a little smaller so it leaves cleaner room for the detail panel.",
    tone: "fixed",
    highlights: [
      "Adjusted only the mobile 3D camera sizing presets for small, medium, and large modes.",
      "Kept the desktop 3D sizing unchanged.",
      "Preserved the larger premium viewer feel while reducing overlap with the mobile details panel.",
    ],
  },
  {
    version: "2.1.3",
    releasedAt: "May 18, 2026",
    title: "Wants Quick View modal hotfix",
    summary: "Wants Quick View now opens as a real popup on mobile instead of expanding inside the binder tile.",
    tone: "fixed",
    highlights: [
      "Moved Wants Quick View into a portal-based modal rendered outside the tile layout.",
      "Kept the binder tile height stable when opening Quick View on mobile.",
      "Preserved the dark glassy modal styling, backdrop close behavior, and internal scrolling.",
    ],
  },
  {
    version: "2.1.2",
    releasedAt: "May 18, 2026",
    title: "Mobile tab and quick view polish",
    summary: "Collection breakdown, segmented tabs, card detail actions, and Wants Quick View received a tighter mobile polish pass.",
    tone: "fixed",
    highlights: [
      "Made the portfolio breakdown shorter on phones while keeping values, counts, and percentages readable.",
      "Removed the extra outer frame around the collection view tabs so only the segmented control remains.",
      "Standardized mobile segmented tabs across collection, movers, settings, account, and sync views with no horizontal tab scrolling.",
      "Gave the card detail remove action a subtle destructive red tint that still fits the dark premium UI.",
      "Changed Wants Quick View into a safe-area-aware floating mobile popup with its own scrollable body and clear close behavior.",
    ],
  },
  {
    version: "2.1.1",
    releasedAt: "May 18, 2026",
    title: "Mobile hover and card tile cleanup",
    summary: "Mobile hover information is now accessible without extra card tile info buttons, and card detail action icons are better aligned.",
    tone: "fixed",
    highlights: [
      "Added a mobile long-press tooltip layer for hover-only labels and title/aria-label information.",
      "Removed the extra info button from card tiles so tapping the card itself opens the full details.",
      "Centered the remove icon inside the card detail action button.",
      "Made Pull Rate hover panels clearer on mobile by changing the hint to Tap and focusing the panel on tap.",
    ],
  },
  {
    version: "2.1.0",
    releasedAt: "May 18, 2026",
    title: "Compact mobile detail controls",
    summary: "Card detail actions, collection tabs, 3D viewing, and price history controls were tightened for mobile without changing the DustyCards look.",
    tone: "improved",
    highlights: [
      "Moved card detail actions into a compact top-right icon group with admin-only History and Refresh controls.",
      "Made the collection overview tabs fit on mobile without horizontal scrolling and preserved scroll position when switching tabs.",
      "Removed the bulky mobile modal header and kept close buttons floating with safe tap targets.",
      "Restored the 3D card viewer to a larger premium size while preventing close taps from reopening the card.",
      "Placed Price History language buttons next to Raw and Graded so the controls take less vertical space.",
    ],
  },
  {
    version: "2.0.1",
    releasedAt: "May 18, 2026",
    title: "Mobile collection polish",
    summary: "Collection overview, card detail, 3D view, and price history panels are now easier to use on small screens.",
    tone: "fixed",
    highlights: [
      "Made the collection breakdown cards readable on mobile with one or two columns instead of cramped three-column truncation.",
      "Changed overview tabs into mobile-safe scrollable tabs that keep every label reachable and readable.",
      "Compacted the card detail header and action row on phones while keeping desktop behavior intact.",
      "Reduced mobile price chart height and replaced noisy technical status text with clearer live price chips.",
      "Improved modal width, safe-area spacing, scroll-to-top behavior, and 3D close handling so the card cannot reopen from the same tap.",
    ],
  },
  {
    version: "2.0.0",
    releasedAt: "May 18, 2026",
    title: "Binder and graded card upgrade",
    summary: "Mobile binder flows, graded slabs, 3D card viewing, and collection spend language received a bigger polish pass.",
    tone: "new",
    highlights: [
      "Bumped the app release to 2.0.0 for the larger binder and graded card refresh.",
      "Changed binder spend language to Overall Spend so shared collection costs read more clearly.",
      "Moved Add Binder on mobile into a centered floating popup and made linked binder suggestions harder to miss.",
      "Added BGS subgrade entry when adding or editing graded BGS cards, while keeping the selected raw condition attached to the graded copy.",
      "Improved BGS slab previews and added a real BGS slab treatment in the 3D card viewer.",
      "Matched the PSA slab back in the 3D viewer more closely to the existing PSA card model.",
      "Added an Add button beside CardMarket inside the 3D card model view.",
      "Reduced holo effect readability loss so card text stays sharper while preserving the foil feel.",
      "Added a mobile 4-up binder/card grid option and a tap info popup for mobile card details.",
      "Cleaned up the Illustrators header so its stats no longer duplicate the same count.",
    ],
  },
  {
    version: "1.1.0",
    releasedAt: "May 18, 2026",
    title: "Dashboard and workflow refresh",
    summary: "Collection, Wants, Movers, search, admin tooling, and pricing behavior were cleaned up into a bigger release.",
    tone: "new",
    highlights: [
      "Bumped the app release to 1.1.0 for the larger dashboard and workflow refresh.",
      "Rebuilt the Collection header into a dashboard layout with a live value chart, stat cards, and game switcher.",
      "Added the Collection Breakdown panel for raw, graded, and sealed value mix with a cleaner allocation bar.",
      "Moved the Breakdown panel above the collection view tabs and matched it to the main header styling.",
      "Replaced the old collection tab buttons with the shared segmented navigation component.",
      "Rebuilt the Wants header with the same dashboard chart and stat card layout as Collection.",
      "Split Wants page content into a cleaner client section so search and planner state are easier to manage.",
      "Upgraded Wants binder quick view into a modal with binder artwork, progress, stats, and a full binder link.",
      "Added quick view sorting by number, price, and name.",
      "Added quick view filters for all, priced, and unpriced missing cards.",
      "Added search match previews inside want binder tiles.",
      "Rebuilt the Movers header with market pulse charting, stat cards, game switcher, scope controls, and source controls.",
      "Removed duplicated Movers control strips from the value, raw, graded, target, and sealed mover sections.",
      "Added shared GameFilterSwitch and SegmentedNavLinks components for consistent navigation controls.",
      "Improved search for exact printed numbers like 002/203.",
      "Improved search for compact printed references like 002203 and space-separated references like 2 203.",
      "Stopped exact printed-number searches from falling into fuzzy fallback when there is no exact match.",
      "Made short text search less noisy by matching tiny text tokens by prefix instead of broad substring hits.",
      "Added tests for printed-number search aliases, exact search behavior, and short text matching.",
      "Added admin-only Firecrawl settings in Settings.",
      "Added the /api/admin/firecrawl endpoint with server-side admin checks.",
      "Added Firecrawl API key and monthly credit budget configuration in the env example.",
      "Ignored local .firecrawl output so scraped/debug files do not get committed accidentally.",
      "Aligned price refreshes to shared tier slots instead of private rolling countdowns per card.",
      "Updated price refresh labels and tests for shared 12h and daily schedules.",
      "Added card detail collection location labels and a remove-saved-copy action.",
      "Polished BGS slab previews with a proper gold label and grade descriptors.",
      "Added fixed range and hidden range-control support to price charts.",
      "Improved chart touch behavior on mobile.",
      "Reduced BGS 10 grading target scores so harder grades are weighted more realistically.",
      "Improved card browser toolbar layouts, including compact toolbar mode without search.",
      "Stretched grid layouts more consistently across search, categories, illustrators, expansions, movers, wants, and binders.",
      "Added portfolio and wants layout sizing variables for more consistent header panel heights.",
    ],
  },
  {
    version: "1.0.25",
    releasedAt: "May 17, 2026",
    title: "Roadmap focus update",
    summary: "The roadmap now reflects that price intelligence is complete and the next work is admin data quality plus Deal Radar v2.",
    tone: "system",
    highlights: [
      "Marked the price intelligence layer as completed.",
      "Added an admin-only data quality center as the next diagnostics step.",
      "Moved Deal Radar v2 into next-up focus for confidence, risk, shipping, and seller context.",
    ],
  },
  {
    version: "1.0.24",
    releasedAt: "May 17, 2026",
    title: "Sealed language charts",
    summary: "Sealed product charts now handle CardMarket language prices the same way card detail does.",
    tone: "improved",
    highlights: [
      "Sealed detail now has Market, EU, DE, FR, ES, and IT chart series where data is available.",
      "The selected sealed series drives the chart, current price, 7D average, and 30D average.",
      "Removed the duplicate language price rows so sealed pricing looks cleaner and closer to normal cards.",
    ],
  },
  {
    version: "1.0.23",
    releasedAt: "May 17, 2026",
    title: "Sealed detail and sync polish",
    summary: "Sealed product detail, pricing freshness, local sync safety, modal styling, and promo numbers were cleaned up.",
    tone: "improved",
    highlights: [
      "Sealed product detail now matches the normal card detail layout more closely.",
      "Card detail is clearer about eBay sold pricing freshness and avoids stale graded values overriding stronger raw prices.",
      "Local development no longer runs background price sync unless it is explicitly enabled.",
      "Collection popups now share the same clean glassy action row without the old dark footer bar.",
      "Black Star promo card numbers now show the printed single promo number, such as SM241.",
    ],
  },
  {
    version: "1.0.22",
    releasedAt: "May 17, 2026",
    title: "Card metadata restored",
    summary: "Card tiles show the card number and clickable set name again.",
    tone: "fixed",
    highlights: [
      "Restored the original collection card metadata line.",
      "Restored set links in card rows and grids where they were available before.",
    ],
  },
  {
    version: "1.0.21",
    releasedAt: "May 17, 2026",
    title: "Cleaner card number labels",
    summary: "Card grids now keep the printed card number visible without repeating the same set name on every card.",
    tone: "improved",
    highlights: [
      "Collection card rows, tables, and tiles now show only the card number in the compact meta line.",
      "Expansion card rows and grids use the same cleaner number-only treatment.",
    ],
  },
  {
    version: "1.0.20",
    releasedAt: "May 17, 2026",
    title: "Printed card numbers",
    summary: "Cards can now show and search the number printed on the card, like 144/131.",
    tone: "new",
    highlights: [
      "Added stored printed card numbers separate from the raw sync number.",
      "Backfilled Pokemon printed references from TCGdex official set counts.",
      "Search can match printed references while keeping sync-safe raw numbers intact.",
    ],
  },
  {
    version: "1.0.19",
    releasedAt: "May 17, 2026",
    title: "Want quick view number clarity",
    summary: "Card numbers in want binder quick view are easier to read.",
    tone: "improved",
    highlights: [
      "Card number badges are larger and higher contrast.",
      "Mobile quick view keeps card identity easier to scan.",
    ],
  },
  {
    version: "1.0.18",
    releasedAt: "May 17, 2026",
    title: "Wantlist quick view polish",
    summary: "Want binder quick view is cleaner, focused, and can add cards directly.",
    tone: "improved",
    highlights: [
      "Quick view rows now prioritize card image, name, number, and rarity.",
      "Prices are smaller so the missing card info is easier to scan.",
      "Quick view card rows are clickable and open card detail.",
      "Only one quick view opens at once, without stretching the full tile row.",
      "The old hide button is now an add-to-binder action.",
    ],
  },
  {
    version: "1.0.17",
    releasedAt: "May 17, 2026",
    title: "Want binder detail pages",
    summary: "Wantlist binder tiles now open a full binder-style missing cards page.",
    tone: "improved",
    highlights: [
      "Clicking a want binder opens a dedicated page with header, chart, and missing cards.",
      "Planner tiles keep the same compact footprint as collection binders.",
      "Quick view is still available as a small secondary action on each tile.",
    ],
  },
  {
    version: "1.0.16",
    releasedAt: "May 17, 2026",
    title: "Want binder tile sizing",
    summary: "Wantlist planner binder tiles now match the collection binder tile footprint.",
    tone: "fixed",
    highlights: [
      "Uses the same fixed tile width as collection binders.",
      "Collapsed wants tiles no longer show the extra top-missing block.",
      "Missing cards stay available after clicking the binder tile open.",
    ],
  },
  {
    version: "1.0.15",
    releasedAt: "May 17, 2026",
    title: "Wantlist planner polish",
    summary: "Binder wants now load immediately and use clickable binder-style tiles.",
    tone: "improved",
    highlights: [
      "Missing binder wants are prepared before the Wants page renders.",
      "Planner binders now look like collection binder tiles with wants-focused metrics.",
      "Clicking a binder tile opens the missing card list directly inside the tile.",
    ],
  },
  {
    version: "1.0.14",
    releasedAt: "May 17, 2026",
    title: "Roadmap status cleanup",
    summary: "Wantlist planner is now marked completed in the roadmap.",
    tone: "improved",
    highlights: [
      "Added a completed roadmap state.",
      "Marked Wantlist planner as completed after the live release.",
      "Kept the upcoming roadmap focused on the next larger features.",
    ],
  },
  {
    version: "1.0.13",
    releasedAt: "May 17, 2026",
    title: "Wantlist planner",
    summary: "Linked binder missing cards now flow into Wants automatically.",
    tone: "new",
    highlights: [
      "Missing cards from linked set binders are added to Wants without a manual repair step.",
      "Wants now groups binder goals into a compact Missing by Binder planner.",
      "Hiding a planner card keeps it out of auto-sync until hidden cards are reset.",
    ],
  },
  {
    version: "1.0.12",
    releasedAt: "May 17, 2026",
    title: "Card detail cleanup",
    summary: "Removed the noisy price intelligence strip from card detail.",
    tone: "fixed",
    highlights: [
      "Kept the compact price status line under the chart.",
      "Removed duplicated confidence, source, freshness, sample, and history tiles.",
      "Card detail is cleaner again on desktop and mobile.",
    ],
  },
  {
    version: "1.0.11",
    releasedAt: "May 17, 2026",
    title: "Price intelligence layer",
    summary: "Card detail now explains price confidence instead of only showing raw numbers.",
    tone: "new",
    highlights: [
      "Added compact confidence, source, freshness, and history signals under the price chart.",
      "eBay sold graded prices now show sample quality and USD to EUR conversion context.",
      "Thin-data warnings make noisy prices easier to spot before buying or selling.",
    ],
  },
  {
    version: "1.0.9",
    releasedAt: "May 17, 2026",
    title: "Roadmap cleanup",
    summary: "Roadmap now focuses on bigger product improvements instead of small bug-fix tasks.",
    tone: "improved",
    highlights: [
      "Removed bug-fix style roadmap items.",
      "Added larger feature ideas for collection, deals, grading, alerts, and sharing.",
      "Kept Japanese support visible as waiting on TCGGO data.",
    ],
  },
  {
    version: "1.0.8",
    releasedAt: "May 17, 2026",
    title: "Expanded roadmap",
    summary: "Roadmap now lists more useful longer-term app improvements.",
    tone: "improved",
    highlights: [
      "Added Japanese support as a waiting-on-data-source item.",
      "Added clearer next improvements for pricing, collection, sync, and mobile UX.",
      "Roadmap stays compact inside the Updates tab.",
    ],
  },
  {
    version: "1.0.7",
    releasedAt: "May 17, 2026",
    title: "Patch notes and roadmap",
    summary: "Added a compact Updates tab in Settings so every release has a clear note.",
    tone: "new",
    highlights: [
      "New Patch Notes window in Settings.",
      "Small roadmap section for upcoming app polish.",
      "Patch notes are stored in a dedicated app file for each release.",
    ],
  },
  {
    version: "1.0.6",
    releasedAt: "May 17, 2026",
    title: "Smarter binder tiles",
    summary: "Binder tiles now show what the set is doing, not only lifetime P&L.",
    tone: "improved",
    highlights: [
      "Added completion percentage and missing card count.",
      "Added recent binder value movement with percent change.",
      "Added ROI under P&L while keeping the tile compact on mobile.",
    ],
  },
  {
    version: "1.0.5",
    releasedAt: "May 17, 2026",
    title: "Consistent slab previews",
    summary: "Card detail slabs now match the same visual style used on collection overview tiles.",
    tone: "fixed",
    highlights: [
      "Removed the separate detail slab look.",
      "Matched wrapper, sizing behavior, and tile styling.",
      "Checked desktop and mobile card detail layouts.",
    ],
  },
  {
    version: "1.0.4",
    releasedAt: "May 17, 2026",
    title: "Account page refresh",
    summary: "Account was rebuilt into a cleaner, more professional account area.",
    tone: "improved",
    highlights: [
      "New account overview layout.",
      "Cleaner security and admin sections.",
      "Better mobile spacing and account stats.",
    ],
  },
  {
    version: "1.0.3",
    releasedAt: "May 16, 2026",
    title: "Settings control center",
    summary: "Settings was reorganized into focused tabs with less duplicate information.",
    tone: "improved",
    highlights: [
      "Added Preferences, Collection, System, and Sync tabs.",
      "Grouped related controls into smaller panels.",
      "Moved sync tooling into one cleaner control area.",
    ],
  },
];

export const roadmapItems: RoadmapItem[] = [
  {
    title: "Japanese card support",
    status: "Waiting",
    summary: "Add Japanese library and price flows when TCGGO exposes reliable Japanese data.",
  },
  {
    title: "Price intelligence layer",
    status: "Completed",
    summary: "Source confidence, eBay sold sample context, currency conversion, stale-price handling, and thin-data warnings are now visible in card and sealed detail.",
  },
  {
    title: "Admin data quality center",
    status: "Next",
    summary: "Admin-only diagnostics for missing images, missing source URLs, stale prices, empty histories, and unavailable price states.",
  },
  {
    title: "Price alerts and watch rules",
    status: "Planned",
    summary: "Let users watch cards, binders, sealed, and wants for target prices or sudden movement.",
  },
  {
    title: "Portfolio analytics",
    status: "Planned",
    summary: "Track allocation by set, era, rarity, language, graded/raw, sealed, and total exposure.",
  },
  {
    title: "Binder goals",
    status: "Planned",
    summary: "Rank missing cards by price, rarity, completion impact, and best next buys for each binder.",
  },
  {
    title: "Grading decision helper",
    status: "Planned",
    summary: "Compare raw value, graded comps, expected grade upside, fees, and likely ROI.",
  },
  {
    title: "Deal Radar v2",
    status: "Next",
    summary: "Add match confidence, risk flags, shipping impact, seller context, and target-margin presets.",
  },
  {
    title: "Wantlist planner",
    status: "Completed",
    summary: "Missing cards from linked binders are now automatically grouped into Wants.",
  },
  {
    title: "Sealed portfolio tools",
    status: "Planned",
    summary: "Track sealed entry price, market movement, position size, ROI, and product-level liquidity.",
  },
  {
    title: "Market timeline",
    status: "Planned",
    summary: "Create a clean timeline of collection value changes, biggest movers, buys, and sold/listing events.",
  },
  {
    title: "Smart collection import",
    status: "Planned",
    summary: "Import CSV or pasted lists, auto-match cards, detect duplicates, and preview changes before saving.",
  },
  {
    title: "Collection export center",
    status: "Planned",
    summary: "Export collection, binders, sealed, wants, and valuation snapshots for backup or spreadsheets.",
  },
  {
    title: "Shareable binder pages",
    status: "Planned",
    summary: "Generate read-only public or private links for selected binders and portfolio views.",
  },
  {
    title: "Personal dashboard widgets",
    status: "Planned",
    summary: "Let users choose which overview modules appear first, with compact cards for their workflow.",
  },
];
