export const KNOWN_UNAVAILABLE_PRICE_STATUS = "unavailable";
export const UPCOMING_PRICE_SOURCE_STATUS = "upcoming";
export const CARDMARKET_NO_EN_NM_PRICE_STATUS = "cardmarket-no-en-nm";

export const NON_ACTIONABLE_MISSING_PRICE_STATUSES = [
  KNOWN_UNAVAILABLE_PRICE_STATUS,
  UPCOMING_PRICE_SOURCE_STATUS,
  CARDMARKET_NO_EN_NM_PRICE_STATUS,
] as const;
