export const KNOWN_UNAVAILABLE_PRICE_STATUS = "unavailable";
export const UPCOMING_PRICE_SOURCE_STATUS = "upcoming";

export const NON_ACTIONABLE_MISSING_PRICE_STATUSES = [
  KNOWN_UNAVAILABLE_PRICE_STATUS,
  UPCOMING_PRICE_SOURCE_STATUS,
] as const;
